/// <reference lib="webworker" />
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'
import { registerRoute, NavigationRoute, Route } from 'workbox-routing'
import { CacheFirst, StaleWhileRevalidate, NetworkFirst } from 'workbox-strategies'
import { ExpirationPlugin } from 'workbox-expiration'
import { BackgroundSyncPlugin } from 'workbox-background-sync'
import { clientsClaim } from 'workbox-core'

declare const self: ServiceWorkerGlobalScope

// Take control of all pages immediately on activation.
clientsClaim()

// Clean up caches from old SW versions.
cleanupOutdatedCaches()

// Pre-cache all static assets generated by Vite (injected by vite-plugin-pwa).
precacheAndRoute(self.__WB_MANIFEST)

// ── Static Asset Caching: CacheFirst ─────────────────────────────────────────
// Fonts, icons, images — these never change for a given URL (content-hashed).
const staticAssetsRoute = new Route(
  ({ request }) =>
    request.destination === 'font' ||
    request.destination === 'image' ||
    request.destination === 'style' ||
    request.destination === 'script',
  new CacheFirst({
    cacheName: 'static-assets-v1',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 200,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
        purgeOnQuotaError: true,
      }),
    ],
  })
)
registerRoute(staticAssetsRoute)

// ── API Caching: StaleWhileRevalidate ─────────────────────────────────────────
// Supabase REST API calls — serve cached data while fetching fresh.
const supabaseApiRoute = new Route(
  ({ url }) => url.hostname.endsWith('.supabase.co') && url.pathname.startsWith('/rest/'),
  new StaleWhileRevalidate({
    cacheName: 'supabase-api-v1',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 5, // 5 minutes
      }),
    ],
  })
)
registerRoute(supabaseApiRoute)

// ── Supabase Auth: NetworkFirst ───────────────────────────────────────────────
// Auth endpoints must always try network first.
const supabaseAuthRoute = new Route(
  ({ url }) => url.hostname.endsWith('.supabase.co') && url.pathname.startsWith('/auth/'),
  new NetworkFirst({
    cacheName: 'supabase-auth-v1',
    networkTimeoutSeconds: 3,
    plugins: [new ExpirationPlugin({ maxEntries: 5, maxAgeSeconds: 60 })],
  })
)
registerRoute(supabaseAuthRoute)

// ── Google Fonts: CacheFirst ──────────────────────────────────────────────────
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com' || url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts-v1',
    plugins: [
      new ExpirationPlugin({ maxEntries: 20, maxAgeSeconds: 60 * 60 * 24 * 365 }),
    ],
  })
)

// ── Background Sync for offline mutations ─────────────────────────────────────
const bgSyncPlugin = new BackgroundSyncPlugin('task-mutations-queue', {
  maxRetentionTime: 60 * 24 * 7, // retry for 7 days
})

registerRoute(
  ({ url, request }) =>
    url.hostname.endsWith('.supabase.co') &&
    url.pathname.startsWith('/rest/') &&
    ['POST', 'PATCH', 'DELETE'].includes(request.method),
  new NetworkFirst({
    cacheName: 'mutations-v1',
    plugins: [bgSyncPlugin],
    networkTimeoutSeconds: 5,
  }),
  'POST'
)

// ── App Shell: NavigationRoute ────────────────────────────────────────────────
// All navigation requests (HTML) fall back to the cached index.html.
const indexRoute = new NavigationRoute(
  new NetworkFirst({
    cacheName: 'app-shell-v1',
    networkTimeoutSeconds: 3,
    plugins: [new ExpirationPlugin({ maxEntries: 5, maxAgeSeconds: 60 * 60 * 24 })],
  })
)
registerRoute(indexRoute)

// ── Skip Waiting with user confirmation ───────────────────────────────────────
// When the client sends 'SKIP_WAITING', activate the new SW immediately.
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    void self.skipWaiting()
  }
})

// ── Push Notifications ────────────────────────────────────────────────────────
self.addEventListener('push', (event) => {
  const data = event.data?.json() as { title?: string; body?: string; url?: string } | undefined
  const title = data?.title ?? 'To-DoList by Azlan'
  const body = data?.body ?? "You have tasks waiting for you."
  const url = data?.url ?? '/'

  const notifOptions: NotificationOptions = {
    body,
    icon: '/icons/pwa-192x192.png',
    badge: '/icons/pwa-64x64.png',
    tag: 'todolist-azlan-notification',
    data: { url },
  }

  event.waitUntil(self.registration.showNotification(title, notifOptions))
})

self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  if (event.action === 'dismiss') return

  const url = (event.notification.data as { url?: string }).url ?? '/'

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if (client.url === url && 'focus' in client) {
          return client.focus()
        }
      }
      return self.clients.openWindow(url)
    })
  )
})

// ── Periodic Sync (background task refresh) ───────────────────────────────────
self.addEventListener('periodicsync', (event) => {
  const syncEvent = event as Event & { tag: string; waitUntil: (p: Promise<unknown>) => void }
  if (syncEvent.tag === 'refresh-tasks') {
    syncEvent.waitUntil(
      fetch(`${self.location.origin}/api/tasks/ping`, { credentials: 'include' }).catch(() => {
        // Network unavailable — IndexedDB is the source of truth.
      })
    )
  }
})
